version: "{build}"
skip_tags: true
environment:
  matrix:
    - PYTHON: "C:\\Python26"
      PYTHON_ID: "26"
      PYTHON_EXE: python
    - PYTHON: "C:\\Python26-x64"
      PYTHON_ID: "26-x64"
      PYTHON_EXE: python
    - PYTHON: "C:\\Python27"
      PYTHON_ID: "27"
      PYTHON_EXE: python
    - PYTHON: "C:\\Python27-x64"
      PYTHON_ID: "27-x64"
      PYTHON_EXE: python
    - PYTHON: "C:\\Python33"
      PYTHON_ID: "33"
      PYTHON_EXE: python
    - PYTHON: "C:\\Python33-x64"
      PYTHON_ID: "33-x64"
      PYTHON_EXE: python
    - PYTHON: "C:\\pypy2-v5.3.1-win32"
      PYTHON_ID: "pypy"
      PYTHON_EXE: pypy
install:
  - ps: |-
      $env:PYTMP = "${env:TMP}\py";
      if (!(Test-Path "$env:PYTMP")) {
        New-Item -ItemType directory -Path "$env:PYTMP" | Out-Null;
      }

      if ("${env:PYTHON_ID}" -eq "pypy") {
        if (!(Test-Path "${env:PYTMP}\pypy2-v5.3.1-win32.zip")) {
          (New-Object Net.WebClient).DownloadFile('https://bitbucket.org/pypy/pypy/downloads/pypy2-v5.3.1-win32.zip', "${env:PYTMP}\pypy2-v5.3.1-win32.zip");
        }
        7z x -y "${env:PYTMP}\pypy2-v5.3.1-win32.zip" -oC:\ | Out-Null;
        if (!(Test-Path "${env:PYTMP}\get-pip.py")) {
          (New-Object Net.WebClient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', "${env:PYTMP}\get-pip.py");
        }
        & "${env:PYTHON}\pypy.exe" "${env:PYTMP}\get-pip.py";
        & "${env:PYTHON}\bin\pip.exe" --disable-pip-version-check --quiet install flake8;
        & "${env:PYTHON}\bin\pip.exe" --disable-pip-version-check --quiet install https://github.com/wbond/asn1crypto/archive/master.zip;
        & "${env:PYTHON}\bin\pip.exe" --disable-pip-version-check --quiet install https://github.com/wbond/oscrypto/archive/master.zip;

      } elseif ("${env:PYTHON_ID}" -eq "26" -or "${env:PYTHON_ID}" -eq "26-x64") {
        # Skip flake8 for 2.6 since pip, flake8 and pycodestyle have all deprecated support for it
        (New-Object Net.WebClient).DownloadFile('https://github.com/wbond/asn1crypto/archive/master.zip', "${env:TMP}\asn1crypto-master.zip");
        7z x -y "${env:TMP}\asn1crypto-master.zip" -o"${env:TMP}\" | Out-Null;
        (New-Object Net.WebClient).DownloadFile('https://github.com/wbond/oscrypto/archive/master.zip', "${env:TMP}\oscrypto-master.zip");
        7z x -y "${env:TMP}\oscrypto-master.zip" -o"${env:TMP}\" | Out-Null;
        $origDir = "$pwd";
        cd "${env:TMP}\asn1crypto-master\";
        & "${env:PYTHON}\python.exe" setup.py install clean;
        cd "${env:TMP}\oscrypto-master\";
        & "${env:PYTHON}\python.exe" setup.py install clean;
        cd "$origDir";

      } else {
        & "${env:PYTHON}\Scripts\pip.exe" --disable-pip-version-check --quiet install flake8;
        & "${env:PYTHON}\Scripts\pip.exe" --disable-pip-version-check --quiet install https://github.com/wbond/asn1crypto/archive/master.zip;
        & "${env:PYTHON}\Scripts\pip.exe" --disable-pip-version-check --quiet install https://github.com/wbond/oscrypto/archive/master.zip;
      }
  - "SET PATH=%PYTHON%;%PATH%"
cache:
  - '%TMP%\py\'
build: off
test_script:
  - cmd: "%PYTHON_EXE% run.py ci"
